services:
  server:
    build:
      context: .
      target: final
    ports:
      - 5000:5000
    secrets:
     - config
    environment:
     - mode=docker
    image: zvup/test-repo:senec-monitor-latest
secrets:
  config:
    file: .docker.env

