services:
  server:
    build:
      context: .
      target: final
    ports:
      - 6600:6000
    secrets:
     - config
    environment:
     - mode=docker
    image: zvup/test-repo:senec-monitor-latest
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: yourpass
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    volumes:
     - pgdata:/var/lib/postgresql/data
     - ./docker-db/initFiles:/docker-entrypoint-initdb.d
    ports:
      - 6000:5432
  pgAdmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: "your@mail.com"
        PGADMIN_DEFAULT_PASSWORD: "yourpass"
      ports:
        - 5050:80
      depends_on:
        - db
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 300
    restart: always
    command: --label-enable

volumes:
  pgdata:
  pgInit:
     driver: local
secrets:
  config:
    file: .docker.env

